/**
 * Permission catalogue, mirroring `Permissions.java` on the backend.
 *
 * The backend remains the authority: these constants only let the UI hide or
 * disable actions the current user cannot perform, so the portal never offers
 * a button that is going to come back as a 403.
 */
export const Permission = {
  USER_VIEW: 'USER_VIEW',
  USER_MANAGE: 'USER_MANAGE',
  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_MANAGE: 'ROLE_MANAGE',

  ORGANIZATION_VIEW: 'ORGANIZATION_VIEW',
  ORGANIZATION_MANAGE: 'ORGANIZATION_MANAGE',

  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',

  METAL_VIEW: 'METAL_VIEW',
  METAL_MANAGE: 'METAL_MANAGE',
  METAL_RATE_PUBLISH: 'METAL_RATE_PUBLISH',

  GEMSTONE_VIEW: 'GEMSTONE_VIEW',
  GEMSTONE_MANAGE: 'GEMSTONE_MANAGE',

  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_CREATE: 'INVENTORY_CREATE',
  INVENTORY_TRANSFER: 'INVENTORY_TRANSFER',
  INVENTORY_TRANSFER_APPROVE: 'INVENTORY_TRANSFER_APPROVE',
  INVENTORY_RESERVE: 'INVENTORY_RESERVE',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',

  PRICE_CHANGE: 'PRICE_CHANGE',
  DISCOUNT_REQUEST: 'DISCOUNT_REQUEST',
  DISCOUNT_APPROVE: 'DISCOUNT_APPROVE',

  SUPPLIER_VIEW: 'SUPPLIER_VIEW',
  SUPPLIER_MANAGE: 'SUPPLIER_MANAGE',

  CUSTOMER_VIEW: 'CUSTOMER_VIEW',
  CUSTOMER_MANAGE: 'CUSTOMER_MANAGE',
  CUSTOMER_KYC_VERIFY: 'CUSTOMER_KYC_VERIFY',

  PROCUREMENT_VIEW: 'PROCUREMENT_VIEW',
  PROCUREMENT_CREATE: 'PROCUREMENT_CREATE',
  PROCUREMENT_APPROVE: 'PROCUREMENT_APPROVE',
  PROCUREMENT_RECEIVE: 'PROCUREMENT_RECEIVE',

  SALE_VIEW: 'SALE_VIEW',
  SALE_CREATE: 'SALE_CREATE',
  SALE_RETURN: 'SALE_RETURN',

  PAYMENT_VIEW: 'PAYMENT_VIEW',
  PAYMENT_COLLECT: 'PAYMENT_COLLECT',
  PAYMENT_REFUND: 'PAYMENT_REFUND',
  PAYMENT_RECONCILE: 'PAYMENT_RECONCILE',

  EXCHANGE_VIEW: 'EXCHANGE_VIEW',
  EXCHANGE_PROCESS: 'EXCHANGE_PROCESS',
  EXCHANGE_VALUE: 'EXCHANGE_VALUE',
  EXCHANGE_APPROVE: 'EXCHANGE_APPROVE',

  REPAIR_VIEW: 'REPAIR_VIEW',
  REPAIR_PROCESS: 'REPAIR_PROCESS',
  REPAIR_ESTIMATE: 'REPAIR_ESTIMATE',

  WAREHOUSE_VIEW: 'WAREHOUSE_VIEW',
  WAREHOUSE_MANAGE: 'WAREHOUSE_MANAGE',
  STOCK_COUNT_PERFORM: 'STOCK_COUNT_PERFORM',
  STOCK_COUNT_APPROVE: 'STOCK_COUNT_APPROVE',

  NOTIFICATION_VIEW: 'NOTIFICATION_VIEW',
  NOTIFICATION_MANAGE: 'NOTIFICATION_MANAGE',

  CRM_VIEW: 'CRM_VIEW',
  CRM_MANAGE: 'CRM_MANAGE',
  CAMPAIGN_MANAGE: 'CAMPAIGN_MANAGE',

  LOYALTY_VIEW: 'LOYALTY_VIEW',
  LOYALTY_MANAGE: 'LOYALTY_MANAGE',
  LOYALTY_REDEEM: 'LOYALTY_REDEEM',
  LOYALTY_ADJUST: 'LOYALTY_ADJUST',

  AUDIT_VIEW: 'AUDIT_VIEW',
  FILE_UPLOAD: 'FILE_UPLOAD',
  FILE_DOWNLOAD: 'FILE_DOWNLOAD',

  FINANCE_VIEW: 'FINANCE_VIEW',
  FINANCE_MANAGE: 'FINANCE_MANAGE',
  FINANCE_POST: 'FINANCE_POST',

  REPORT_VIEW: 'REPORT_VIEW',
  COMPLIANCE_REPORT: 'COMPLIANCE_REPORT',
} as const;

export type PermissionCode = (typeof Permission)[keyof typeof Permission];

/**
 * A permission requirement attached to a route or UI element.
 *
 * A single code, or a list which is satisfied when the user holds *any* of the
 * codes. `requireAll` on the route data flips that to *every*.
 */
export type PermissionRequirement = PermissionCode | readonly PermissionCode[];
