/**
 * Single registry of backend endpoint paths, relative to the API prefix.
 *
 * Feature services must resolve their URLs from here rather than embedding
 * string literals, so a backend route change is a one-file edit.
 */
export const ApiEndpoints = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    logoutAll: '/auth/logout-all',
    changePassword: '/auth/change-password',
    me: '/auth/me',
  },
  organization: {
    companies: '/companies',
    company: (id: string) => `/companies/${id}`,
    branches: '/branches',
    branch: (id: string) => `/branches/${id}`,
    branchLocations: (branchId: string) => `/branches/${branchId}/locations`,
    locations: '/locations',
    location: (id: string) => `/locations/${id}`,
  },
  users: {
    root: '/users',
    byId: (id: string) => `/users/${id}`,
    resetPassword: (id: string) => `/users/${id}/reset-password`,
  },
  roles: {
    root: '/roles',
    byId: (id: string) => `/roles/${id}`,
    permissions: '/permissions',
  },
  catalogue: {
    categories: '/product-categories',
    category: (id: string) => `/product-categories/${id}`,
    productTypes: '/product-types',
    productType: (id: string) => `/product-types/${id}`,
    brands: '/brands',
    collections: '/collections',
    sizes: '/sizes',
    designs: '/designs',
    design: (id: string) => `/designs/${id}`,
    products: '/products',
    product: (id: string) => `/products/${id}`,
  },
  metals: {
    root: '/metals',
    byId: (id: string) => `/metals/${id}`,
    purities: (metalId: string) => `/metals/${metalId}/purities`,
    createPurity: '/purities',
    purity: (id: string) => `/purities/${id}`,
    rates: '/metal-rates',
    currentRate: '/metal-rates/current',
  },
  gemstones: {
    root: '/gemstones',
    byId: (id: string) => `/gemstones/${id}`,
    certificates: '/stone-certificates',
    itemStones: (itemId: string) => `/jewellery-items/${itemId}/stones`,
  },
  inventory: {
    items: '/inventory/items',
    item: (id: string) => `/inventory/items/${id}`,
    itemByTag: '/inventory/items/by-tag',
    passport: (id: string) => `/inventory/items/${id}/passport`,
    tag: (id: string) => `/inventory/items/${id}/tags`,
    release: (id: string) => `/inventory/items/${id}/release`,
    changeStatus: (id: string) => `/inventory/items/${id}/status`,
    reservations: '/inventory/reservations',
    releaseReservation: (id: string) => `/inventory/items/${id}/release-reservation`,
    transfers: '/inventory/transfers',
    transfer: (id: string) => `/inventory/transfers/${id}`,
    approveTransfer: (id: string) => `/inventory/transfers/${id}/approve`,
    rejectTransfer: (id: string) => `/inventory/transfers/${id}/reject`,
    dispatchTransfer: (id: string) => `/inventory/transfers/${id}/dispatch`,
    receiveTransfer: (id: string) => `/inventory/transfers/${id}/receive`,
    cancelTransfer: (id: string) => `/inventory/transfers/${id}/cancel`,
  },
  reports: {
    sales: '/reports/sales',
    inventoryValuation: '/reports/inventory-valuation',
    stockAgeing: '/reports/stock-ageing',
    loyaltyLiability: '/reports/loyalty-liability',
  },
  suppliers: {
    root: '/suppliers',
    byId: (id: string) => `/suppliers/${id}`,
    status: (id: string) => `/suppliers/${id}/status`,
    contacts: (id: string) => `/suppliers/${id}/contacts`,
    bankAccounts: (id: string) => `/suppliers/${id}/bank-accounts`,
  },
  procurement: {
    requisitions: '/procurement/requisitions',
    requisition: (id: string) => `/procurement/requisitions/${id}`,
    approveRequisition: (id: string) => `/procurement/requisitions/${id}/approve`,
    rejectRequisition: (id: string) => `/procurement/requisitions/${id}/reject`,
    orders: '/procurement/purchase-orders',
    order: (id: string) => `/procurement/purchase-orders/${id}`,
    approveOrder: (id: string) => `/procurement/purchase-orders/${id}/approve`,
    rejectOrder: (id: string) => `/procurement/purchase-orders/${id}/reject`,
    cancelOrder: (id: string) => `/procurement/purchase-orders/${id}/cancel`,
    closeOrder: (id: string) => `/procurement/purchase-orders/${id}/close`,
    receipts: '/procurement/goods-receipts',
    receipt: (id: string) => `/procurement/goods-receipts/${id}`,
    acceptReceipt: (id: string) => `/procurement/goods-receipts/${id}/accept`,
    rejectReceipt: (id: string) => `/procurement/goods-receipts/${id}/reject`,
    invoices: '/procurement/supplier-invoices',
  },
  pricing: {
    calculate: '/pricing/calculate',
    makingChargeRules: '/pricing/making-charge-rules',
    makingChargeRule: (id: string) => `/pricing/making-charge-rules/${id}`,
    taxRates: '/pricing/tax-rates',
    taxRate: (id: string) => `/pricing/tax-rates/${id}`,
    discountPolicies: '/pricing/discount-policies',
  },
  customers: {
    root: '/customers',
    byId: (id: string) => `/customers/${id}`,
    byPhone: '/customers/by-phone',
    addresses: (id: string) => `/customers/${id}/addresses`,
    documents: (id: string) => `/customers/${id}/documents`,
    kyc: (id: string) => `/customers/${id}/kyc`,
    preferences: (id: string) => `/customers/${id}/preferences`,
    status: (id: string) => `/customers/${id}/status`,
  },
  crm: {
    customer360: (id: string) => `/crm/customers/${id}/360`,
    activities: '/crm/activities',
    followUps: '/crm/follow-ups',
    myFollowUps: '/crm/follow-ups/mine',
    completeFollowUp: (id: string) => `/crm/follow-ups/${id}/complete`,
    cancelFollowUp: (id: string) => `/crm/follow-ups/${id}/cancel`,
    segments: '/crm/segments',
    segment: (id: string) => `/crm/segments/${id}`,
    segmentMembers: (id: string) => `/crm/segments/${id}/members`,
    campaigns: '/crm/campaigns',
    campaign: (id: string) => `/crm/campaigns/${id}`,
    campaignPreview: (id: string) => `/crm/campaigns/${id}/preview`,
  },
  loyalty: {
    programs: '/loyalty/programs',
    program: (id: string) => `/loyalty/programs/${id}`,
    programActive: (id: string) => `/loyalty/programs/${id}/active`,
    account: (customerId: string) => `/loyalty/accounts/${customerId}`,
    statement: (customerId: string) => `/loyalty/accounts/${customerId}/transactions`,
    accounts: '/loyalty/accounts',
    redemptions: '/loyalty/redemptions',
    adjustments: '/loyalty/adjustments',
  },
  sales: {
    quotations: '/quotations',
    quotation: (id: string) => `/quotations/${id}`,
    cancelQuotation: (id: string) => `/quotations/${id}/cancel`,
    root: '/sales',
    byId: (id: string) => `/sales/${id}`,
    cancel: (id: string) => `/sales/${id}/cancel`,
    deliver: (id: string) => `/sales/${id}/deliver`,
    returns: (id: string) => `/sales/${id}/returns`,
    dailyClosing: '/sales/daily-closing',
  },
  payments: {
    root: '/payments',
    forSale: (saleId: string) => `/sales/${saleId}/payments`,
    refunds: '/payments/refunds',
    reconcile: (id: string) => `/payments/${id}/reconcile`,
  },
  exchanges: {
    root: '/exchanges',
    byId: (id: string) => `/exchanges/${id}`,
    weigh: (id: string) => `/exchanges/${id}/weigh`,
    purityTest: (id: string) => `/exchanges/${id}/purity-test`,
    valuation: (id: string) => `/exchanges/${id}/valuation`,
    approve: (id: string) => `/exchanges/${id}/approve`,
    reject: (id: string) => `/exchanges/${id}/reject`,
    complete: (id: string) => `/exchanges/${id}/complete`,
    returnToCustomer: (id: string) => `/exchanges/${id}/return`,
  },
  repairs: {
    root: '/repairs',
    byId: (id: string) => `/repairs/${id}`,
    overdue: '/repairs/overdue',
    inspection: (id: string) => `/repairs/${id}/inspection`,
    estimate: (id: string) => `/repairs/${id}/estimate`,
    customerDecision: (id: string) => `/repairs/${id}/customer-decision`,
    assign: (id: string) => `/repairs/${id}/assign`,
    completeWork: (id: string) => `/repairs/${id}/complete-work`,
    qualityCheck: (id: string) => `/repairs/${id}/quality-check`,
    deliver: (id: string) => `/repairs/${id}/deliver`,
    cancel: (id: string) => `/repairs/${id}/cancel`,
  },
  warehouse: {
    bins: '/warehouse/bins',
    bin: (id: string) => `/warehouse/bins/${id}`,
    stockCounts: '/warehouse/stock-counts',
    stockCount: (id: string) => `/warehouse/stock-counts/${id}`,
    submitCount: (id: string) => `/warehouse/stock-counts/${id}/submit`,
    approveCount: (id: string) => `/warehouse/stock-counts/${id}/approve`,
    cancelCount: (id: string) => `/warehouse/stock-counts/${id}/cancel`,
  },
  finance: {
    accounts: '/finance/accounts',
    account: (id: string) => `/finance/accounts/${id}`,
    ledger: (id: string) => `/finance/accounts/${id}/ledger`,
    journalEntries: '/finance/journal-entries',
    journalEntry: (id: string) => `/finance/journal-entries/${id}`,
    reverseEntry: (id: string) => `/finance/journal-entries/${id}/reverse`,
    trialBalance: '/finance/reports/trial-balance',
    profitAndLoss: '/finance/reports/profit-and-loss',
    balanceSheet: '/finance/reports/balance-sheet',
    receivablesAgeing: '/finance/reports/receivables-ageing',
  },
  compliance: {
    highValue: '/compliance/reports/high-value-transactions',
    structuring: '/compliance/reports/possible-structuring',
    kycStatus: '/compliance/reports/kyc-status',
    dualAuthorisation: '/compliance/reports/dual-authorisation',
    auditSummary: '/compliance/reports/audit-summary',
  },
  auditLogs: {
    root: '/audit-logs',
  },
  files: {
    upload: '/files',
    download: (id: string) => `/files/${id}`,
  },
  notifications: {
    root: '/notifications',
    templates: '/notifications/templates',
    template: (id: string) => `/notifications/templates/${id}`,
    templateActive: (id: string) => `/notifications/templates/${id}/active`,
  },
} as const;
